### PR TITLE
Add option.suffix and option.modify

### PR DESCRIPTION
**Pull request by btd**
By idea this should replicate behavior of bluebird .promisifyAll

### CODE REVIEW

**Comment by sindresorhus** [comment]
Why? I don't add things just because another module has it. Can you link to the Bluebird docs?

**Comment by btd** [comment]
Well, I do not insist. [Promise.promisifyAll](http://bluebirdjs.com/docs/api/promise.promisifyall.html).
I am just removing non spec usages of promises and replacing them with modules.

**Comment by sindresorhus** [comment]
I'm just interested in knowing why you use those options and for what? I've personally never needed something like that :)

**Comment by btd** [comment]
bluebird's .promisifyAll change target object, by adding new methods with Async suffix.

It is pretty common to use it like:
```
var callbackLib = ...;

Promise.promisifyAll(callbackLib);

// now i can use new and old methods 
callbackLib.callAsync(...).then...

// it is very usefull with libs that do some sort of generation at runtime like massivejs reads schema and create table/view/function at startup and mongoose collections.
```

**Comment by SamVerschueren** [comment]
Functions that needs to be pified are already async, otherwise they don't need `pify`.

**Comment by btd** [comment]
@SamVerschueren if user wants to shoot himself in leg you could not stop him. About your example you need to add suffix.

Not sure i understand your statement:
```
Functions that needs to be pified are already async, otherwise they don't need pify. fs.writeFile is async but just works with a callback. Wrapping it with pify keeps it async, it just changes the "contract".
```
 If you confused with 'Async' suffix in my example, that is just what bluebird uses. I cannot say i like it, but it was done not by me.

**Comment by SamVerschueren** [comment]
> if user wants to shoot himself in leg you could not stop him. About your example you need to add suffix.

Users shouldn't be allowed to shoot themselves in the foot by a dependency. It changes the global behaviour of another dependency. That's simply bad practice. So not sure why we should add it if there are only downsides of using it.

> If you confused with 'Async' suffix in my example, that is just what bluebird uses. I cannot say i like it, but it was done not by me.

Because Bluebird uses the `Async` suffix, they clearly added the option because someone wanted to add `Async` to all the promisified methods. So what I was saying was, why do you want to add `Async` to the method name while the original method already is async.
But ok, they could've made the example with `Promise` as a suffic which would result in `fs.writeFilePromise`. But as said before, why would we want to mimic the behaviour of `Bluebird` and bloat the library with extra options that (almost) nobody will use?

**Comment by btd** [comment]
>  But as said before, why would we want to mimic the behaviour of Bluebird and bloat the library with extra options that (almost) nobody will use?
It is a pretty strong statement. I do not really think these 2 options will 'bloat' this library.

But again as i already said i do not insist, it is not my module - and you as collaborator can merge or do not merge, for me both ok. Purpose of this pull request to do not create at npm one more library.
And i think it still will be usefull for anyone migrating out of blubird to smaller modules. 
So feel free to close it if think these 2 options will bloat this module.

**Comment by sindresorhus** [comment]
Sorry @btd. I don't think it makes sense here.

Thanks for the suggestion though. Always appreciated 😀

**Pull request closed without merging**
