### PR TITLE
add prototype support

### PR DESCRIPTION
**Pull request by SamVerschueren**
Needed #14 as well. Not sure if their are any downsides by using `for...in` instead of `Object.keys()`?

@sindresorhus you talked about a boolean flag for promisifying prototype methods or not. Do you still want that? Don't really feel the need for a flag to be able to turn it on or off. So feedback is more then welcome.

### CODE REVIEW

**Comment by sindresorhus** [comment]
@SamVerschueren See https://github.com/sindresorhus/pify/pull/16.

**Comment by SamVerschueren** [comment]
Damn, should've looked better. Title of the PR wasn't entirely clear. Thanks for pointing that out.

**Comment by sindresorhus** [comment]
@SamVerschueren Any feedback on that PR more than welcome! I haven't had a chance to review it yet. Let's discuss the flag thing there.

**Comment by SamVerschueren** [comment]
@sindresorhus sure!

**Pull request closed without merging**
