### PR TITLE
Add default property for typescript support

### PR DESCRIPTION
**Pull request by cstruct**

### CODE REVIEW

**Comment by sindresorhus** [comment]
No thanks. This is how pretty much all node modules work. You can't realistically change them all to get TypeScript support. I'm sure there's another way that doesn't require you to support a pull request to every node module you use.

-

// @SamVerschueren

**Comment by SamVerschueren** [comment]
Just use the `import * as pify from 'pify';` syntax or `import pify = require('pify');`.

Babel 6 generated code now use the `module.exports['default']` syntax and thus follows the ES6 module spec. So probably when ES6 modules become a common thing in the NodeJS world and we can all use `export default ...`, we will all be happy. But as Sindre already said, you can't do a PR for every module you want to use in TypeScript. 

The same goes for the type definitions btw. If you want the, do a PR in `DefinitelyTyped`. Don't expect module owners to take care of all of that. You don't want to know how many people did PR's on Sindre's repositories to solve webpack module resolution. It's the same thing, it's not up to us to take care of that and bloat the module with that stuff.

**Comment by LinusU** [comment]
I would agree if this had anything to do with webpack or similar stuff, but I don't see this as being specific to type script. As you said, this is how it will work in the future when ES6 modules becomes a common thing.

This is about following the ES6 module spec, which makes it compatible with the eco system, not specifically about making it compatible with TypeScript. That being said, I'll respect that you'll have the final say in this since it's your modules to maintain...

**Comment by kevva** [comment]
I'd argue that the compilers should adapt to legacy code rather than the other way around. In the node world, `module.exports` kinda implies `module.exports.default`, like Babel handles it.

**Pull request closed without merging**
